In [5]:
import speech_recognition as sr
recognizer=sr.Recognizer()
with sr.Microphone() as source:
    audio=recognizer.listen(source)
    print(recognizer.recognize_sphinx(audio))

it and no welcome to germinate


In [3]:
import numpy as np
a=np.random.randn(5,5)
a

array([[ 4.61374344e-01, -7.57325304e-01, -6.85858497e-01,
        -6.27649395e-01, -3.62477539e-01],
       [ 1.11661885e+00, -1.05116637e+00, -1.95166825e+00,
        -1.30496294e-01, -7.08046075e-02],
       [ 1.48352166e+00,  1.53481334e+00, -1.74833943e+00,
        -1.49042634e+00, -3.82340939e-01],
       [-1.46834217e+00,  2.37740722e+00,  7.91914556e-01,
         3.03933744e-04,  1.40828364e-01],
       [-1.60897776e+00,  4.99486945e-01, -4.14041787e-01,
         4.49708899e-01,  1.61845267e+00]])

In [5]:
for i in a:
    print(i)

[ 0.46137434 -0.7573253  -0.6858585  -0.6276494  -0.36247754]
[ 1.11661885 -1.05116637 -1.95166825 -0.13049629 -0.07080461]
[ 1.48352166  1.53481334 -1.74833943 -1.49042634 -0.38234094]
[-1.46834217e+00  2.37740722e+00  7.91914556e-01  3.03933744e-04
  1.40828364e-01]
[-1.60897776  0.49948694 -0.41404179  0.4497089   1.61845267]
